controller:
  ros__parameters:
    broadcastTime: 1
    commitmentUpdateTime: 5
    pPerceiveLightSources: 0.1
    numberOfTargets: 4
    colorsOfTargets: ["yellow", "green", "magenta", "brown"]
    fov: 90.0
    commsType: 0
    hardTurnOnAngleThreshold: 50.0
    softTurnOnAngleThreshold: 20.5
    noTurnOnAngleThreshold: 10.0
    maxSpeed: 10.0
    logDirectoryName: "/home/sindiso/ros2_dev/dev-logs"
    experimentName: "10_ticks_per_second"
